usb: typec: tcpc: fix unused variable build breaks
Error:
drivers/misc/mediatek/typec/tcpc/pd_dpm_alt_mode_dp.c:332:6:
error: variable 'local_index' set but not used
[-Werror,-Wunused-but-set-variable]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS06194194
Feature: Kernel SI Operation
Change-Id: Ia4b87b1f4da7993e13d33b6d024370bcdb7b3524